version: '3'
services:
  cmspshoto-backend:
    container_name: cmspshoto-backend
    build: .
    command: npm run server
    ports:
      - ${REDIRECT_PORT}:${PORT}
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


# DOCKER COMMANDS
#   Running 'docker compose up -d' starts the containers in the background
#
#   docker build . -t black/cmspshoto-backend
#   docker run -p 3001:3001 -d black/cmspshoto-backend
#
#   docker exec -i postgres psql -h localhost near-cms < server/db/migration/init_db.sql postgres
#   docker exec -i postgres psql -h localhost near-cms < server/db/migration/insert_data.sql postgres
#
