DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS variables;

-- user_roles
CREATE TABLE user_roles
(
  id    BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  value VARCHAR(255) UNIQUE                            NOT NULL
);

-- users
CREATE TABLE users
(
  id                   BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  login                VARCHAR(255) UNIQUE                            NOT NULL,
  event                VARCHAR(255)                                   NOT NULL,
  password             VARCHAR(255)                                   NOT NULL,
  passwordExpiryDate   TIMESTAMP                                      NOT NULL,
  permission           BIGINT                                         NOT NULL,
  date        TIMESTAMP,
  expiryDate  TIMESTAMP                                               NOT NULL,
  dir                  VARCHAR(255) UNIQUE                            NOT NULL,
  role_id              BIGINT REFERENCES user_roles (id)              NOT NULL,
  PRIMARY KEY (id)
);

-- contract
CREATE TABLE contract
(
  user_id     BIGINT REFERENCES users (id) NOT NULL,
  contract    BOOLEAN DEFAULT false        NOT NULL,
  pdf         VARCHAR(255),
  price       NUMERIC(5, 2),
  advance     NUMERIC(5, 2),
  howMuchPaid NUMERIC(5, 2)
);

-- permissions
CREATE TABLE permissions
(
  id          BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(255) UNIQUE                            NOT NULL,
  value       INT unique                                     NOT NULL,
  deleteValue INT unique                                     NOT NULL,
  description VARCHAR(255) unique                            NOT NULL
);

-- variables
CREATE TABLE variables
(
  id       BIGINT UNIQUE GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  property VARCHAR(255) unique                            NOT NULL,
  value    VARCHAR(255)                                   NOT NULL
);

\i '/var/www/html/all/nodejs-express-and-reactjs-CMS/server/db/migration/insert_data.sql';
